site:
  title: Antora Test Docs Site
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://fabianfnc.github.io/bocs/
  start_page: antoratest::introduction.adoc
content:
  sources:
    - url: https://github.com/fabianfnc/bocs.git
      branches: 'master'
      start_path: doc

ui:
  bundle:
    url: https://github.com/fabianfnc/bocs/blob/master/doc/uibundle.zip?raw=true
    snapshot: true